pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Pull Request
      - base=master
    actions:
      merge:
        method: merge
